config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'main#index'

  resources :time_entries
  resources :categories, except: :show
  
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'user_time_logs', to: 'reports#user_time'
  get 'category_time_logs', to: 'reports#category_time'
end

app/views/shared/time_table/_table_body.html.haml
- t.each do |t_entry|
  %tr
    %td= display_time_entry(t_entry.start, :short)
    %td= display_time_entry(t_entry.stop, :short)
    %td= display_duration(t_entry)
    %td.text-center= display_comment(t_entry)
    %td.text-center= display_category(t_entry)
    - if controls
      %td= link_to '', edit_time_entry_path(t_entry), class: "fa fa-edit fa-2x"
      %td= link_to '', t_entry, method: :delete, data: { confirm: 'Are you sure to delete this time entry?' }, class: "fa fa-trash fa-2x"
- if total
  %tr.total-duration
    %td.text-right{:colspan => "2"}
      %strong TOTAL
    %td{:colspan => "3"}
      = display_total_hours(@time_entries)

app/views/shared/time_table/_table_head.html.haml
%table#time-entries-table
  %thead
    %tr
      %th{:width => "15%"} Start
      %th{:width => "15%"} Stop
      %th{:width => "15%"}
        Duration
        %br/
        (hh:mm:ss)
      %th.text-center Comment
      %th.text-center{:width => "20%"} Category
      - if controls
        %th{:colspan => "2", :width => "10%"}
  %tbody
    = render "shared/time_table/table_body", t: time_entries, controls: controls, total: total