config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'main#index'

  resources :time_entries
  resources :categories, except: :show
  
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'user_time_logs', to: 'reports#user_time'
  get 'category_time_logs', to: 'reports#category_time'
end

app/views/shared/_close_button.html.haml
%button.close-button{'aria-label' => 'Dismiss alert', 'data-close' => ''}
  %span{'aria-hidden' => 'true'} &times;

app/views/shared/_error_box.html.haml
- if obj.errors.any?
  .callout.alert.small
    %h5 Please correct errors: 
    %ul
      - obj.errors.each do |error|
        %li= error.full_message

app/views/shared/_flash.html.haml
- if flash[:notice]
  .cell.flash-notice
    .callout.primary{'data-closable' => ''}
      = flash[:notice]
      = render "shared/close_button"
- if flash[:error]
  .cell.flash-error
    .callout.alert{'data-closable' => ''}
      = flash[:error]
      = render "shared/close_button"

app/views/shared/_footer.html.haml
.grid-x
  .cell.small-6
    %p Follow on social media: 
    %a.fa.fa-twitter{:href => "https://twitter.com/milikkan", :target => "_blank"}
    %a.fa.fa-github-alt{:href => "https://github.com/milikkan", :target => "_blank"}
    %a.fa.fa-linkedin{:href => "https://www.linkedin.com/in/mustafa-il%C4%B1kkan-33142b74/", :target => "_blank"}
  .cell.small-6.copyright
    %p.text-right &copy; Time Logger App, 2021

app/views/shared/_menu_left.html.haml
- if Current.user
  %li= link_to "My Time Logs", time_entries_path
  %li= link_to "New Entry", new_time_entry_path
  - if Current.user.is_admin
    = render "shared/menu_left_admin"

app/views/shared/_menu_left_admin.html.haml
%li
  = link_to "Admin", user_time_logs_path
  %ul.menu.vertical
    %li= link_to "User Time Logs", user_time_logs_path
    %li= link_to "Category Time Logs", category_time_logs_path
    %li= link_to "Categories", categories_path
    %li= link_to "Users", users_path

app/views/shared/_topbar.html.haml
.top-bar
  .top-bar-left
    %ul.menu.dropdown{"data-dropdown-menu" => ""}
      %li.fa.fa-hourglass.brand-icon.fa-2x
      %li= link_to "TIME LOGGER", root_path, class: "menu-text"
      = render "shared/menu/menu_left"
  .top-bar-right
    = render "shared/menu/menu_right"